import os


BASE_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(BASE_PATH,'datas')
# DATA_PATH_FILE = os.path.join(DATA_PATH,'api.xlsx')
DATA_PATH_FILE = os.path.join(DATA_PATH,'case_data.xlsx')
NEW_DATA_PATH_FILE = os.path.join(DATA_PATH,'new_data.xlsx')
AIDONG_DATA_PATH_FILE = os.path.join(DATA_PATH,'aidong.xlsx')
NEW_API_DATA_PATH = os.path.join(DATA_PATH,'new_api.xlsx')
ORDER_API_DATA_PATH = os.path.join(DATA_PATH, "order_system.xlsx")
# print(AIDONG_DATA_PATH_FILE)
CONFIG_PATH = os.path.join(BASE_PATH,'config')
CONFIG_PATH_FILE = os.path.join(CONFIG_PATH,'config.ini')
CONFIG_TOKEN_PATH = os.path.join(CONFIG_PATH,'token_data.ini')
API_TOKEN_PATH = os.path.join(CONFIG_PATH,'api_token.ini')
print(API_TOKEN_PATH)
# print(CONFIG_TOKEN_PATH)
# print(CONFIG_PATH_FILE)
LOG_PATH = os.path.join(BASE_PATH,'log')
LOG_PATH_FILE = os.path.join(LOG_PATH,'log.txt')
# print(LOG_PATH_FILE)
REPORT_PATH = os.path.join(BASE_PATH,'report')
USER_ACCOUNTS_FILE_PATH = os.path.join(CONFIG_PATH, 'user_account.ini')
# print(USER_ACCOUNTS_FILE_PATH)
CASES_PATH = os.path.join(BASE_PATH,'case2')
